### ISSUE TITLE
Plugin depends on deprecated modules

### ISSUE THREAD

**Issue by jorgemia** [padarom/vuepress-plugin-code-switcher#4]
When trying to install this package I got the following warnings:

```
warning vuepress-plugin-code-switcher > @vuepress/plugin-register-components > @vuepress/shared-utils > globby > fast-glob > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning vuepress-plugin-code-switcher > @vuepress/plugin-register-components > @vuepress/shared-utils > globby > fast-glob > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
```

Don't know if you have to update this on your end but the creator of those modules suggests:

>  "make your dependency chain update to source-map-resolve version 0.6.0 or later, or switch to dependencies not using source-map-resolve at all."

**Comment by padarom** [comment]
I have updated `@vuepress/plugin-register-components` to 1.8.0 (I realized I was still using the alpha version, since that was what I had originally developed this plugin with). Still, the dependency chain eventually points to `source-map-resolve`.

There isn't really anything I can do about this, as this dependency is needed to make the custom component available, so this would have to be reported upstream at @vuepress.
