### ISSUE TITLE
possible to pass page variables into code block?

### ISSUE THREAD

**Issue by ssuess** [padarom/vuepress-plugin-code-switcher#7]
Hi is it possible to pass vuepress page variables into the code blocks? I have been trying unsuccessfully with variations of:
```
<CodeSwitcher>
<template v-slot:curl>

```
```bash
curl --location --request GET $page.relativePath.split('/')[1].split('.md')[0]

```
```

</template>
<CodeSwitcher>
```

**Comment by ssuess** [comment]
well I figured it out partially, I can do this:
```
<pre><code>curl --location --request GET {{$page.relativePath.split('/')[1].split('.md')[0]}}</code></pre>
```

but then I lose my prism highlighting

**Comment by padarom** [comment]
This seems related to https://github.com/vuejs/vuepress/issues/413. The issue I see is that if the code can change, then so needs its highlighting. The highlighting does not seem to be reactive though.

That's why for interpolated `<code>` blocks the syntax highlighting is disabled.

Crafting a solution for this  unfortunately is outside the scope of this plugin.
